version: "3.8"

services:
  db:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "fonasa"
      MYSQL_USER: "nexoos"
      MYSQL_PASSWORD: "nexoos"
      MYSQL_ROOT_PASSWORD: "nexoos"
    volumes:
      - mysql_data:/var/lib/mysql

  fonasa_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  mysql_data:
