"""empty message

Revision ID: 5f3ccd55089a
Revises: 
Create Date: 2024-01-03 21:42:34.703331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3ccd55089a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('noHistoriaClinica', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('tieneDieta', sa.Boolean(), nullable=True),
    sa.Column('fumador', sa.Boolean(), nullable=True),
    sa.Column('relacionPesoEstatura', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantPacientes', sa.Integer(), nullable=True),
    sa.Column('nombreEspecialista', sa.String(length=100), nullable=True),
    sa.Column('tipoConsulta', sa.Enum('GENERAL', 'ESPECIALIZADA', name='tipoconsulta'), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'PENDIENTE', name='estado'), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consulta')
    op.drop_table('paciente')
    op.drop_table('hospital')
    # ### end Alembic commands ###
